version: '3'

services: 
  portal-financeiro-api:
    image: 'node:10.16.0-alpine'
    working_dir: '/home/portal-financeiro-api'
    volumes: 
      - ./:/home/portal-financeiro-api
    command: "sh -c 'npm install && npm run dev'"
    depends_on:
      - portal-financeiro-db
    environment:
      NODE_ENV: development
    ports: 
      - 9002:3000
    expose:
      - "9002"
  portal-financeiro-db:
    image: 'mongo:4'